// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   uint64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string               `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PasswordHash         []byte               `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPasswordHash() []byte {
	if m != nil {
		return m.PasswordHash
	}
	return nil
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type CreateUserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             []byte   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{1}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

type CreateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{2}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type FindUserRequest struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindUserRequest) Reset()         { *m = FindUserRequest{} }
func (m *FindUserRequest) String() string { return proto.CompactTextString(m) }
func (*FindUserRequest) ProtoMessage()    {}
func (*FindUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{3}
}

func (m *FindUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserRequest.Unmarshal(m, b)
}
func (m *FindUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserRequest.Marshal(b, m, deterministic)
}
func (m *FindUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserRequest.Merge(m, src)
}
func (m *FindUserRequest) XXX_Size() int {
	return xxx_messageInfo_FindUserRequest.Size(m)
}
func (m *FindUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserRequest proto.InternalMessageInfo

func (m *FindUserRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type FindUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindUserResponse) Reset()         { *m = FindUserResponse{} }
func (m *FindUserResponse) String() string { return proto.CompactTextString(m) }
func (*FindUserResponse) ProtoMessage()    {}
func (*FindUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{4}
}

func (m *FindUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserResponse.Unmarshal(m, b)
}
func (m *FindUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserResponse.Marshal(b, m, deterministic)
}
func (m *FindUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserResponse.Merge(m, src)
}
func (m *FindUserResponse) XXX_Size() int {
	return xxx_messageInfo_FindUserResponse.Size(m)
}
func (m *FindUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserResponse proto.InternalMessageInfo

func (m *FindUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type VerifyUserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             []byte   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyUserRequest) Reset()         { *m = VerifyUserRequest{} }
func (m *VerifyUserRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyUserRequest) ProtoMessage()    {}
func (*VerifyUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{5}
}

func (m *VerifyUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyUserRequest.Unmarshal(m, b)
}
func (m *VerifyUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyUserRequest.Marshal(b, m, deterministic)
}
func (m *VerifyUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyUserRequest.Merge(m, src)
}
func (m *VerifyUserRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyUserRequest.Size(m)
}
func (m *VerifyUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyUserRequest proto.InternalMessageInfo

func (m *VerifyUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *VerifyUserRequest) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

type VerifyUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyUserResponse) Reset()         { *m = VerifyUserResponse{} }
func (m *VerifyUserResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyUserResponse) ProtoMessage()    {}
func (*VerifyUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{6}
}

func (m *VerifyUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyUserResponse.Unmarshal(m, b)
}
func (m *VerifyUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyUserResponse.Marshal(b, m, deterministic)
}
func (m *VerifyUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyUserResponse.Merge(m, src)
}
func (m *VerifyUserResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyUserResponse.Size(m)
}
func (m *VerifyUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyUserResponse proto.InternalMessageInfo

func (m *VerifyUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*CreateUserRequest)(nil), "user.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "user.CreateUserResponse")
	proto.RegisterType((*FindUserRequest)(nil), "user.FindUserRequest")
	proto.RegisterType((*FindUserResponse)(nil), "user.FindUserResponse")
	proto.RegisterType((*VerifyUserRequest)(nil), "user.VerifyUserRequest")
	proto.RegisterType((*VerifyUserResponse)(nil), "user.VerifyUserResponse")
}

func init() { proto.RegisterFile("user/user.proto", fileDescriptor_ed89022014131a74) }

var fileDescriptor_ed89022014131a74 = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xcd, 0x8e, 0x9b, 0x30,
	0x18, 0x94, 0x53, 0x9a, 0x26, 0x5f, 0xd2, 0xa6, 0xb1, 0xda, 0x06, 0x71, 0x68, 0x11, 0xbd, 0xa0,
	0x1e, 0x40, 0x25, 0xbd, 0xe4, 0x14, 0xb5, 0x55, 0xaa, 0xf6, 0x4a, 0x7f, 0x0e, 0xbd, 0x20, 0x07,
	0x1c, 0xb0, 0x36, 0xc4, 0xac, 0x6d, 0x76, 0xb5, 0xef, 0xb0, 0x4f, 0xb6, 0x4f, 0xb5, 0xc2, 0x84,
	0x80, 0xc2, 0x25, 0xd2, 0x5e, 0x90, 0xe7, 0xf3, 0x30, 0x33, 0xdf, 0x08, 0x60, 0x56, 0x4a, 0x2a,
	0xfc, 0xea, 0xe1, 0x15, 0x82, 0x2b, 0x8e, 0x8d, 0xea, 0x6c, 0x7d, 0x48, 0x39, 0x4f, 0xf7, 0xd4,
	0xd7, 0xb3, 0x6d, 0xb9, 0xf3, 0x15, 0xcb, 0xa9, 0x54, 0x24, 0x2f, 0x6a, 0x9a, 0x73, 0x8f, 0xc0,
	0xf8, 0x2b, 0xa9, 0xc0, 0xaf, 0x60, 0xc0, 0x12, 0x13, 0xd9, 0xc8, 0x35, 0xc2, 0x01, 0x4b, 0xf0,
	0x1b, 0x78, 0x4e, 0x73, 0xc2, 0xf6, 0xe6, 0xc0, 0x46, 0xee, 0x38, 0xac, 0x01, 0xfe, 0x08, 0x2f,
	0x0b, 0x22, 0xe5, 0x2d, 0x17, 0x49, 0x94, 0x11, 0x99, 0x99, 0xcf, 0x6c, 0xe4, 0x4e, 0xc3, 0x69,
	0x33, 0xfc, 0x49, 0x64, 0x86, 0x57, 0x00, 0xb1, 0xa0, 0x44, 0xd1, 0x24, 0x22, 0xca, 0x34, 0x6c,
	0xe4, 0x4e, 0x02, 0xcb, 0xab, 0x93, 0x78, 0x4d, 0x12, 0xef, 0x4f, 0x93, 0x24, 0x1c, 0x1f, 0xd9,
	0x5f, 0x95, 0xb3, 0x81, 0xf9, 0x77, 0x0d, 0xaa, 0x4c, 0x21, 0xbd, 0x2e, 0xa9, 0x54, 0x6d, 0x14,
	0xd4, 0x8d, 0x62, 0xc1, 0xa8, 0x71, 0xd5, 0x19, 0xa7, 0xe1, 0x09, 0x3b, 0x5f, 0x00, 0x77, 0x65,
	0x64, 0xc1, 0x0f, 0x92, 0xe2, 0xf7, 0xa0, 0x4b, 0xd1, 0x32, 0x93, 0x00, 0x3c, 0xdd, 0x96, 0x66,
	0xe8, 0xb9, 0xf3, 0x09, 0x66, 0x3f, 0xd8, 0x21, 0xe9, 0x5a, 0x2f, 0xe0, 0x45, 0x75, 0x15, 0x9d,
	0xaa, 0x19, 0x56, 0xf0, 0x57, 0xe2, 0x04, 0xf0, 0xba, 0xe5, 0x5e, 0xa8, 0xbf, 0x81, 0xf9, 0x3f,
	0x2a, 0xd8, 0xee, 0xee, 0xc9, 0xcb, 0x75, 0x65, 0x2e, 0x33, 0x0f, 0x1e, 0x10, 0x4c, 0x2a, 0xf8,
	0x9b, 0x8a, 0x1b, 0x16, 0x53, 0xbc, 0x06, 0x68, 0x2b, 0xc2, 0x8b, 0x9a, 0xdf, 0xeb, 0xde, 0x32,
	0xfb, 0x17, 0x47, 0xc3, 0x15, 0x8c, 0x9a, 0x06, 0xf0, 0xdb, 0x9a, 0x75, 0xd6, 0x9e, 0xf5, 0xee,
	0x7c, 0x7c, 0x7c, 0x75, 0x0d, 0xd0, 0x6e, 0xd0, 0x78, 0xf7, 0xaa, 0x69, 0xbc, 0xfb, 0xcb, 0x7e,
	0x5b, 0xfe, 0xff, 0x9c, 0x32, 0x95, 0x95, 0x5b, 0x2f, 0xe6, 0xb9, 0x9f, 0x13, 0x59, 0x1e, 0x78,
	0x4e, 0x14, 0xbb, 0xe2, 0x7e, 0x2a, 0x8a, 0x38, 0x52, 0xa5, 0xe2, 0x82, 0x91, 0x7d, 0x50, 0x7f,
	0xf8, 0xfa, 0xbf, 0xd8, 0x0e, 0xf5, 0x79, 0xf9, 0x18, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x6b, 0x1b,
	0xf1, 0x2b, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	FindUser(ctx context.Context, in *FindUserRequest, opts ...grpc.CallOption) (*FindUserResponse, error)
	VerifyUser(ctx context.Context, in *VerifyUserRequest, opts ...grpc.CallOption) (*VerifyUserResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) FindUser(ctx context.Context, in *FindUserRequest, opts ...grpc.CallOption) (*FindUserResponse, error) {
	out := new(FindUserResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/FindUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) VerifyUser(ctx context.Context, in *VerifyUserRequest, opts ...grpc.CallOption) (*VerifyUserResponse, error) {
	out := new(VerifyUserResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/VerifyUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	FindUser(context.Context, *FindUserRequest) (*FindUserResponse, error)
	VerifyUser(context.Context, *VerifyUserRequest) (*VerifyUserResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedUserServiceServer) FindUser(ctx context.Context, req *FindUserRequest) (*FindUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindUser not implemented")
}
func (*UnimplementedUserServiceServer) VerifyUser(ctx context.Context, req *VerifyUserRequest) (*VerifyUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyUser not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_FindUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).FindUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/FindUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).FindUser(ctx, req.(*FindUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_VerifyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).VerifyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/VerifyUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).VerifyUser(ctx, req.(*VerifyUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "FindUser",
			Handler:    _UserService_FindUser_Handler,
		},
		{
			MethodName: "VerifyUser",
			Handler:    _UserService_VerifyUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/user.proto",
}
